services:
  internship-system:
    image: internship-system
    build:
      context: .
      dockerfile: Internship-system.API/Dockerfile
    restart: always
    environment:
      - CONNECTIONSTRINGS__DATABASE=User ID=postgres;Password=postgres;Host=postgres;Port=5432;Database=inter-db
    ports:
        - "7000:8080"
    depends_on:
        - postgres
    volumes:
        - /var/log/internship:/app/logs
  postgres:
    image: postgres:latest
    command: postgres -c 'max_connections=250'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: